name: build
on: [push]

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v1
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        go vet
        go build -v .

    - name: Test
      run: |
        go test -v -race -cover

